#!/bin/bash

set -eu

# Create a Drush command alias that can be run from anywhere in the filesystem
# and that resets the file cache folders/files permissions after each Drush
# command run. We do not do this using a bash alias or function because they
# wouldn't be available to `docker run` or `docker-compose exec`.
CURRENT_DIR="${PWD}"
cd "${APP_WEB_ROOT}"

if ! command -v drush &> /dev/null
then
    export PATH="${PATH}":/var/www/html/bin:/var/www/html/vendor/bin
fi

drush "$@"
p caches

cd "${CURRENT_DIR}"
