#!/bin/bash

# Require strict variable naming: This prevents problems with mistyped variable
# names or mistakes in this script.
set -u

if [ $# -eq 0 ]; then
    action="all"
else
    action="$1"
fi

declare -A aliases
aliases["all"]="caches+files"
for alias in "${!aliases[@]}"; do
    if [[ "${action}" == "$alias" ]]; then
        action=${aliases[$alias]}
        break
    fi
done

IFS='+' read -ra TASKS <<< "$action"
if [ ${#TASKS[*]} -gt '1' ]
then
    for task in "${TASKS[@]}"; do
        $0 ${task} "${@:2}"
    done
    exit 0
fi

case "${action}" in
    caches|files)
        printf "[INFO] Resetting permissions for ${action}\n"
        ;;

    *)
        printf "[ERROR] Unsupported task ${action}\n"
        exit 1
        ;;
esac

case "${action}" in
    caches)
        if [ ! -d "${APP_CACHE_DIR}" ]; then
            mkdir -p "${APP_CACHE_DIR}"
        fi
        find "${APP_CACHE_DIR}" -exec chown "${APP_APP_OS_USER}":"${APP_PHP_OS_GROUP}" {} \;
        find "${APP_CACHE_DIR}" -type f -exec chmod 660 {} \;
        find "${APP_CACHE_DIR}" -type d -exec chmod 770 {} \;
        ;;

    files)
        if [ ! -d "${APP_PUBLIC_FILES_DIR}" ]; then
            mkdir -p "${APP_PUBLIC_FILES_DIR}"
        fi
        chown -R "${APP_APP_OS_USER}":"${APP_PHP_OS_GROUP}" "${APP_PUBLIC_FILES_DIR}"
        chmod -R g+w "${APP_PUBLIC_FILES_DIR}"
        find "${APP_PUBLIC_FILES_DIR}" -type d -exec chmod 2775 {} \;
        find "${APP_PUBLIC_FILES_DIR}" -type f -exec chmod 644 {} \;

        if [ ! -d "${APP_PRIVATE_FILES_DIR}" ]; then
            mkdir -p "${APP_PRIVATE_FILES_DIR}"
        fi
        chown -R "${APP_APP_OS_USER}":"${APP_PHP_OS_GROUP}" "${APP_PRIVATE_FILES_DIR}"
        chmod -R g+w "${APP_PRIVATE_FILES_DIR}"
        find "${APP_PRIVATE_FILES_DIR}" -type d -exec chmod 2770 {} \;
        find "${APP_PRIVATE_FILES_DIR}" -type f -exec chmod 640 {} \;
        ;;
esac
